name: audio_chat
description: "The Audio Chat Flutter application."
publish_to: 'none'
version: 2.2.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  rust_builder:
    path: rust_builder

  flutter_rust_bridge: 2.0.0-dev.29
  flutter_secure_storage: ^9.0.0

  shared_preferences: ^2.2.2
  debug_console: ^0.0.1
  mutex: ^3.1.0
  file_picker: ^8.0.0+1
  uuid: ^4.3.3
  collection: any
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/sounds/
   - assets/models/
