name: telepathy
description: "A cross platform p2p chat application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  rust_builder:
    path: rust_builder

  flutter_rust_bridge: 2.10.0
  flutter_secure_storage: ^9.0.0

  shared_preferences: ^2.5.3
  mutex: ^3.1.0
  file_picker: ^10.1.9
  uuid: ^4.3.3
  permission_handler: ^12.0.0+1
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.1.0
  collection: any
  super_clipboard: ^0.8.17
  path_provider: ^2.1.3
  process_run: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/sounds/
   - assets/models/
   - assets/icons/
