[package]
name = "audio_chat"
version = "2.2.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "*", features = ["codec"] }
cpal = "0.15"
prost = "*"
log = "*"
fast_log = "1.6"
kanal = "0.1.0-pre8"
rubato = "0.15"
nnnoiseless = { version = "0.5", default-features = false }
atomic_float = "0.1"
x25519-dalek = { version = "*", features = ["getrandom"] }
ed25519-dalek = { version = "*", features = ["rand_core"] }
rayon = "1.10"
rand = "*"
flutter_rust_bridge = "=2.0.0-dev.29"
parking_lot = "*"
lazy_static = "1.4"
uuid = { version = "1.8", features = ["v4"] }
bytes = "1.6"
common = { path = "../common" }
# TODO webrtc-ice ends up depending on ring which isn't ideal
webrtc-ice = "0.10"
webrtc-sctp = "0.9"
webrtc-util = "0.8"
async-throttle = "0.3"

[build-dependencies]
prost-build = "*"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"
ndk-context = "0.1.1"