display_name: Audio Chat
icon: linux/icon.png
summary: A cross platform p2p chat application
group: Applications/Development Tools
vendor: Chander Luderman Miller
packager: Chander Luderman Miller
packagerEmail: me@chanchan.dev
license: MIT
url: https://github.com/chanderlud/audio-chat

build_arch: x86_64

requires:
  - libsecret

keywords:
  - Audio Chat
  - p2p

generic_name: Audio Chat

categories:
  - Development
  - Utility

startup_notify: true
