display_name: Telepathy
icon: linux/icon.png
summary: A cross-platform P2P chat application
group: Applications/Multimedia
vendor: Chander Luderman Miller
packager: Chander Luderman Miller
packagerEmail: me@chanchan.dev
license: MIT
url: https://github.com/chanderlud/telepathy

requires:
  - libsecret
  - gtk3

keywords:
  - Telepathy
  - p2p

generic_name: Telepathy

categories:
  - Development
  - Utility

startup_notify: true

description: A peer-to-peer cross-platform audio chat application.

postinstall_scripts:
  - echo "Thank you for installing Telepathy!"
