// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Contact>>
@sealed
class Contact extends RustOpaque {
  Contact.dcoDecode(List<dynamic> wire) : super.dcoDecode(wire, _kStaticData);

  Contact.sseDecode(BigInt ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Contact,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Contact,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ContactPtr,
  );

  static Contact fromParts(
          {required String id,
          required String nickname,
          required String peerId,
          dynamic hint}) =>
      RustLib.instance.api.crateApiContactContactFromParts(
          id: id, nickname: nickname, peerId: peerId, hint: hint);

  String id({dynamic hint}) =>
      RustLib.instance.api.crateApiContactContactId(that: this, hint: hint);

  bool idEq({required List<int> id, dynamic hint}) => RustLib.instance.api
      .crateApiContactContactIdEq(that: this, id: id, hint: hint);

  factory Contact(
          {required String nickname, required String peerId, dynamic hint}) =>
      RustLib.instance.api.crateApiContactContactNew(
          nickname: nickname, peerId: peerId, hint: hint);

  String nickname({dynamic hint}) => RustLib.instance.api
      .crateApiContactContactNickname(that: this, hint: hint);

  String peerId({dynamic hint}) =>
      RustLib.instance.api.crateApiContactContactPeerId(that: this, hint: hint);

  Contact pubClone({dynamic hint}) => RustLib.instance.api
      .crateApiContactContactPubClone(that: this, hint: hint);

  void setNickname({required String nickname, dynamic hint}) =>
      RustLib.instance.api.crateApiContactContactSetNickname(
          that: this, nickname: nickname, hint: hint);
}
