// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `Error` is not used by any `pub` functions, thus it is ignored.
// The type `ErrorKind` is not used by any `pub` functions, thus it is ignored.

class DartError implements FrbException {
  final String message;

  const DartError({
    required this.message,
  });

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DartError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}
