// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'audio_chat.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `play_sound`, `processor`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SoundHandle>>
abstract class SoundHandle implements RustOpaqueInterface {
  void cancel();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SoundPlayer>>
abstract class SoundPlayer implements RustOpaqueInterface {
  ArcHost host();

  factory SoundPlayer({required double outputVolume}) => RustLib.instance.api
      .crateApiPlayerSoundPlayerNew(outputVolume: outputVolume);

  /// Public play function
  Future<SoundHandle> play({required List<int> bytes});

  Future<void> updateOutputDevice({String? name});

  void updateOutputVolume({required double volume});
}
