// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'contact.dart';
import 'error.dart';
import 'overlay/overlay.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'player.dart';

// These functions are ignored because they are not marked as `pub`: `_join_room`, `_start_session`, `audio_input`, `audio_output`, `call_controller`, `call`, `get_input_device`, `handshake`, `input_processor`, `latencies_missing`, `loopback`, `new`, `new`, `new`, `open_stream`, `output_processor`, `relayed_only`, `session_manager`, `session`, `statistics_collector`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectionState`, `PeerState`, `SessionState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Capabilities>>
abstract class Capabilities implements RustOpaqueInterface {
  static Future<Capabilities> default_() =>
      RustLib.instance.api.crateApiTelepathyCapabilitiesDefault();

  List<String> devices();

  List<String> encoders();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChatMessage>>
abstract class ChatMessage implements RustOpaqueInterface {
  List<(String, Uint8List)> attachments();

  String get text;

  set text(String text);

  void clearAttachments();

  bool isSender({required String identity});

  String time();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CodecConfig>>
abstract class CodecConfig implements RustOpaqueInterface {
  factory CodecConfig(
          {required bool enabled,
          required bool vbr,
          required double residualBits}) =>
      RustLib.instance.api.crateApiTelepathyCodecConfigNew(
          enabled: enabled, vbr: vbr, residualBits: residualBits);

  void setEnabled({required bool enabled});

  void setResidualBits({required double residualBits});

  void setVbr({required bool vbr});

  (bool, bool, double) toValues();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartNotify>>
abstract class DartNotify implements RustOpaqueInterface {
  /// public notified function for dart
  Future<void> notified();

  /// notifies one waiter
  void notify();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NetworkConfig>>
abstract class NetworkConfig implements RustOpaqueInterface {
  Future<String> getRelayAddress();

  Future<String> getRelayId();

  factory NetworkConfig(
          {required String relayAddress, required String relayId}) =>
      RustLib.instance.api.crateApiTelepathyNetworkConfigNew(
          relayAddress: relayAddress, relayId: relayId);

  Future<void> setRelayAddress({required String relayAddress});

  Future<void> setRelayId({required String relayId});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecordingConfig>>
abstract class RecordingConfig implements RustOpaqueInterface {
  int bitrate();

  String device();

  String encoder();

  int framerate();

  int? height();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ScreenshareConfig>>
abstract class ScreenshareConfig implements RustOpaqueInterface {
  Future<Capabilities> capabilities();

  static Future<ScreenshareConfig> default_() =>
      RustLib.instance.api.crateApiTelepathyScreenshareConfigDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ScreenshareConfig> newInstance({required String configStr}) =>
      RustLib.instance.api
          .crateApiTelepathyScreenshareConfigNew(configStr: configStr);

  Future<RecordingConfig?> recordingConfig();

  @override
  String toString();

  Future<void> updateRecordingConfig(
      {required String encoder,
      required String device,
      required int bitrate,
      required int framerate,
      int? height});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Telepathy>>
abstract class Telepathy implements RustOpaqueInterface {
  /// Blocks while an audio test is running
  Future<void> audioTest();

  ChatMessage buildChat(
      {required Contact contact,
      required String text,
      required List<(String, Uint8List)> attachments});

  /// Ends the call (if there is one)
  void endCall();

  /// Lists the input and output devices
  Future<(List<String>, List<String>)> listDevices();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Telepathy> newInstance(
          {required List<int> identity,
          required ArcHost host,
          required NetworkConfig networkConfig,
          required ScreenshareConfig screenshareConfig,
          required Overlay overlay,
          required CodecConfig codecConfig,
          required FutureOr<bool> Function(String, Uint8List?, DartNotify)
              acceptCall,
          required FutureOr<void> Function(String, bool) callEnded,
          required FutureOr<Contact?> Function(Uint8List) getContact,
          required FutureOr<void> Function(bool) callState,
          required FutureOr<void> Function(String, String) sessionStatus,
          required FutureOr<void> Function(Telepathy) startSessions,
          required FutureOr<void> Function(Statistics) statistics,
          required FutureOr<void> Function(ChatMessage) messageReceived,
          required FutureOr<void> Function(bool, bool) managerActive,
          required FutureOr<void> Function(DartNotify, bool)
              screenshareStarted}) =>
      RustLib.instance.api.crateApiTelepathyTelepathyNew(
          identity: identity,
          host: host,
          networkConfig: networkConfig,
          screenshareConfig: screenshareConfig,
          overlay: overlay,
          codecConfig: codecConfig,
          acceptCall: acceptCall,
          callEnded: callEnded,
          getContact: getContact,
          callState: callState,
          sessionStatus: sessionStatus,
          startSessions: startSessions,
          statistics: statistics,
          messageReceived: messageReceived,
          managerActive: managerActive,
          screenshareStarted: screenshareStarted);

  /// Restarts the session manager
  Future<void> restartManager();

  /// Attempts to start a call through an existing session
  Future<void> sayHello({required Contact contact});

  /// Sends a chat message
  Future<void> sendChat({required ChatMessage message});

  void setDeafened({required bool deafened});

  /// Changing the denoise flag will not affect the current call
  void setDenoise({required bool denoise});

  /// Sets the signing key (called when the profile changes)
  Future<void> setIdentity({required List<int> key});

  Future<void> setInputDevice({String? device});

  void setInputVolume({required double decibel});

  Future<void> setModel({Uint8List? model});

  void setMuted({required bool muted});

  Future<void> setOutputDevice({String? device});

  void setOutputVolume({required double decibel});

  void setPlayCustomRingtones({required bool play});

  void setRmsThreshold({required double decimal});

  void setSendCustomRingtone({required bool send});

  Future<void> startScreenshare({required Contact contact});

  /// Tries to start a session for a contact
  Future<void> startSession({required Contact contact});

  /// Stops a specific session (called when a contact is deleted)
  Future<void> stopSession({required Contact contact});
}

/// processed statistics for the frontend
class Statistics {
  /// a percentage of the max input volume in the window
  final double inputLevel;

  /// a percentage of the max output volume in the window
  final double outputLevel;

  /// the current call latency
  final BigInt latency;

  /// the approximate upload bandwidth used by the current call
  final BigInt uploadBandwidth;

  /// the approximate download bandwidth used by the current call
  final BigInt downloadBandwidth;

  /// a value between 0 and 1 representing the percent of audio lost in a sliding window
  final double loss;

  const Statistics({
    required this.inputLevel,
    required this.outputLevel,
    required this.latency,
    required this.uploadBandwidth,
    required this.downloadBandwidth,
    required this.loss,
  });

  static Future<Statistics> default_() =>
      RustLib.instance.api.crateApiTelepathyStatisticsDefault();

  @override
  int get hashCode =>
      inputLevel.hashCode ^
      outputLevel.hashCode ^
      latency.hashCode ^
      uploadBandwidth.hashCode ^
      downloadBandwidth.hashCode ^
      loss.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Statistics &&
          runtimeType == other.runtimeType &&
          inputLevel == other.inputLevel &&
          outputLevel == other.outputLevel &&
          latency == other.latency &&
          uploadBandwidth == other.uploadBandwidth &&
          downloadBandwidth == other.downloadBandwidth &&
          loss == other.loss;
}
