display_name: Audio Chat
package_name: audio-chat

maintainer:
  name: Chander Luderman Miller
  email: me@chanchan.dev

priority: optional

section: x11

installed_size: 42308

dependencies:
  - libsecret-1-0

essential: false

icon: linux/icon.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Audio Chat
  - p2p

generic_name: Audio Chat

categories:
  - Development
  - Utility

startup_notify: true
