display_name: Telepathy
package_name: telepathy

maintainer:
  name: Chander Luderman Miller
  email: me@chanchan.dev

priority: optional

section: sound

description: "A peer-to-peer audio chat application."

installed_size: 42308

dependencies:
  - libsecret-1-0
  - libgtk-3-0

essential: false

icon: linux/icon.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Telepathy
  - p2p

generic_name: Telepathy

categories:
  - Development
  - Utility

startup_notify: true
